import "../globals.css";
import Nav from "@/components/ui/Nav";
import {TeamsContextProvider} from "@/components/TeamsProvider";
import SideBar from "@/components/ui/SideBar";

export const metadata = {
    title: "Hoop Hub",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (

        <TeamsContextProvider>
            <main className={''}>
            <div className={'flex'}>
                <SideBar />
                {children}
            </div>
            {/*<Footer />*/}
            </main>
        </TeamsContextProvider>

    );
}