export const nbaTeams = [
    { city: "Atlanta", name: "Hawks", logo: "https://upload.wikimedia.org/wikipedia/en/2/24/Atlanta_Hawks_logo.svg" },
    { city: "Boston", name: "Celtics", logo: "https://upload.wikimedia.org/wikipedia/en/8/8f/Boston_Celtics.svg" },
    { city: "Brooklyn", name: "Nets", logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Brooklyn_Nets_newlogo.svg" },
    { city: "Charlotte", name: "Hornets", logo: "https://upload.wikimedia.org/wikipedia/en/c/c4/Charlotte_Hornets_%282014%29.svg" },
    { city: "Chicago", name: "Bulls", logo: "https://upload.wikimedia.org/wikipedia/en/6/67/Chicago_Bulls_logo.svg" },
    { city: "Cleveland", name: "Cavaliers", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cleveland_Cavaliers_logo.svg/340px-Cleveland_Cavaliers_logo.svg.png" },
    { city: "Dallas", name: "Mavericks", logo: "https://upload.wikimedia.org/wikipedia/en/9/97/Dallas_Mavericks_logo.svg" },
    { city: "Denver", name: "Nuggets", logo: "https://upload.wikimedia.org/wikipedia/en/7/76/Denver_Nuggets.svg" },
    { city: "Detroit", name: "Pistons", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_of_the_Detroit_Pistons.svg/400px-Logo_of_the_Detroit_Pistons.svg.png" },
    { city: "Golden State", name: "Warriors", logo: "https://upload.wikimedia.org/wikipedia/en/0/01/Golden_State_Warriors_logo.svg" },
    { city: "Houston", name: "Rockets", logo: "https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Rockets.svg" },
    { city: "Indiana", name: "Pacers", logo: "https://upload.wikimedia.org/wikipedia/en/1/1b/Indiana_Pacers.svg" },
    { city: "Los Angeles", name: "Clippers", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Los_Angeles_Clippers_%282024%29.svg/440px-Los_Angeles_Clippers_%282024%29.svg.png" },
    { city: "Los Angeles", name: "Lakers", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Los_Angeles_Lakers_logo.svg" },
    { city: "Memphis", name: "Grizzlies", logo: "https://upload.wikimedia.org/wikipedia/en/f/f1/Memphis_Grizzlies.svg" },
    { city: "Miami", name: "Heat", logo: "https://upload.wikimedia.org/wikipedia/en/f/fb/Miami_Heat_logo.svg" },
    { city: "Milwaukee", name: "Bucks", logo: "https://upload.wikimedia.org/wikipedia/en/4/4a/Milwaukee_Bucks_logo.svg" },
    { city: "Minnesota", name: "Timberwolves", logo: "https://upload.wikimedia.org/wikipedia/en/c/c2/Minnesota_Timberwolves_logo.svg" },
    { city: "New Orleans", name: "Pelicans", logo: "https://upload.wikimedia.org/wikipedia/en/0/0d/New_Orleans_Pelicans_logo.svg" },
    { city: "New York", name: "Knicks", logo: "https://upload.wikimedia.org/wikipedia/en/2/25/New_York_Knicks_logo.svg" },
    { city: "Oklahoma City", name: "Thunder", logo: "https://upload.wikimedia.org/wikipedia/en/5/5d/Oklahoma_City_Thunder.svg" },
    { city: "Orlando", name: "Magic", logo: "https://upload.wikimedia.org/wikipedia/en/1/10/Orlando_Magic_logo.svg" },
    { city: "Philadelphia", name: "76ers", logo: "https://upload.wikimedia.org/wikipedia/en/0/0e/Philadelphia_76ers_logo.svg" },
    { city: "Phoenix", name: "Suns", logo: "https://upload.wikimedia.org/wikipedia/en/d/dc/Phoenix_Suns_logo.svg" },
    { city: "Portland", name: "Trail Blazers", logo: "https://upload.wikimedia.org/wikipedia/en/2/21/Portland_Trail_Blazers_logo.svg" },
    { city: "Sacramento", name: "Kings", logo: "https://upload.wikimedia.org/wikipedia/en/c/c7/SacramentoKings.svg" },
    { city: "San Antonio", name: "Spurs", logo: "https://upload.wikimedia.org/wikipedia/en/a/a2/San_Antonio_Spurs.svg" },
    { city: "Toronto", name: "Raptors", logo: "https://upload.wikimedia.org/wikipedia/en/3/36/Toronto_Raptors_logo.svg" },
    { city: "Utah", name: "Jazz", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Utah_Jazz_logo_2022.svg/460px-Utah_Jazz_logo_2022.svg.png" },
    { city: "Washington", name: "Wizards", logo: "https://upload.wikimedia.org/wikipedia/en/0/02/Washington_Wizards_logo.svg" },
];

