import localFont from "next/font/local";
import "./globals.css";


export const metadata = {
    title: "Hoop Hub",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Nav/>
        {children}
        </body>
        </html>
    );
}

function Nav() {
    return (
        <div className={'h-12 bg-blue-950'}>
            <div className={'grid grid-cols-3 '}>
                <div className={'bg-yellow-300  flex content-center items-center'}>
                    <div>Yellow</div>
                </div>

                <div className={'bg-red-500 mx-auto'}>
                    Red
                </div>

                <div className={'bg-green-600 ms-auto'}>
                    Green
                </div>
            </div>
        </div>
    )
}
